name: Pipeline

on:
  push:
    branches:
      - development
      - staging
      - main  
jobs: 

  build:  
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x        
    - name: Restore dependencies
      run: dotnet restore      
    - name: Build
      run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    name: Test
    needs: ["build"]
    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x      
    - name: Test
      run: dotnet test --no-build --verbosity normal 

  deploy-staging:
    runs-on: ubuntu-latest
    name: Deploy-Staging
    needs: ["test"]    
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_MOSS_07D6DAC10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"          
          app_location: "Presentation"
          api_location: "Server" 
          output_location: "wwwroot" 

  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy-Production
    needs: ["deploy-staging"]    
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_XXXXXXXXXXXXXXXXXXXX }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"          
          app_location: "Presentation"
          api_location: "Server" 
          output_location: "wwwroot" 